# Generated by Django 4.0.6 on 2022-07-24 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
        migrations.AddField(
            model_name='menu',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
