# Generated by Django 4.0.6 on 2022-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
